import "./globals.css";

import type { Metadata } from "next";
import { Mulish } from "next/font/google";

import { Toaster } from "@/components/ui/sonner";

const mulish = Mulish({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mulish.className} dark antialiased`}>
        <Toaster richColors />
        <main>{children}</main>
      </body>
    </html>
  );
}
